package com.nv.commons.constants;

public enum InternalErrorCodeType {

	REGISTER_NEW_USER_ERROR(),
//	LOGIN_ERROR("2"),
	CHANGE_PASSWORD_ERROR(),
//	FORGET_PASSWORD_ERROR("4"),
	CREATE_ACCOUNT_PROVIDER_ERROR(),
	GET_PLAY_GAME_URL_ERROR(),
//	PAY_GATEWAY_DEPOSIT_ERROR("7"),
//	MONEY_TRANSACTION_DEPOSIT_ERROR("8"),
//	MONEY_TRANSACTION_WITHDRAW_ERROR("9"),
//	TRANSFER_ERROR("10"),
//	LOGOUT_ERROR("11"),
//	PROMOTION_VERIFICATION_ERROR("12"),
//	PAY_GATEWAY_WITHDRAWAL_ERROR("13"),
//	VERIFY_ACCOUNT_ERROR("14"),
	;
}
